# Generated by Django 3.1.1 on 2020-09-29 16:03

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=12)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, unique=True)),
                ('csv_file', models.FileField(upload_to='files')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ManyToManyField(blank=True, to='core.Contact')),
            ],
        ),
    ]
