# Generated by Django 3.1.1 on 2020-09-29 19:36

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_context_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=12)),
                ('file', models.FileField(upload_to='csv_files/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='context',
            name='csv_file',
        ),
        migrations.AddField(
            model_name='context',
            name='csv_files',
            field=models.ManyToManyField(blank=True, to='core.CSVFile'),
        ),
    ]
