# Generated by Django 3.1.1 on 2020-09-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200929_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
