# Generated by Django 3.1.1 on 2020-10-04 09:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
